package amw.informatyka.zadanie1;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : GrSzkoleniowa.java
//  @ Date : 2017-12-22
//  @ Author : 
//
//




public class GrSzkoleniowa {
	public String nazwa;
	public String symbol;
	public String[] przedmioty;
	private Student[] studenci; 
	private int lstudentow = 0;
	
	public static int MAX_STUDENT = 50;
	
	public int addStudent(Student student) {
		getStudenci()[lstudentow++] = student;
		return lstudentow;
	}
	
	public String getNazwa() {
		return nazwa;
	}
	public void setNazwa(String nazwa) {
		this.nazwa = nazwa;
	}
	public String getSymbol() {
		return symbol;
	}
	public void setSymbol(String symbol) {
		this.symbol = symbol;
	}
	public String[] getPrzedmioty() {
		return przedmioty;
	}
	public void setPrzedmioty(String[] przedmioty) {
		this.przedmioty = przedmioty;
	}
	
	private Student[] getStudenci() {
		if (studenci == null)
			studenci = new Student[MAX_STUDENT];
		return studenci;
	}

	public int getLstudentow() {
		return lstudentow;
	}
	
	public void printStudenci() {
		for (int i = 0; i < getStudenci().length; i++) {
			Student s = getStudenci()[i];
			if (s != null)
				System.out.println("Student:"+s);
		}
	}

	@Override
	public String toString() {
		// TODO Auto-generated method stub
		String wynik = new String(getNazwa()+" ("+getSymbol()+')');
		return wynik;
	}
	
	
	
	
}
