package amw.informatyka.zadanie1;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Osoba.java
//  @ Date : 2017-12-22
//  @ Author : 
//
//



public abstract class Osoba {
	public long pesel;
	public String imie;
	public String nazwisko;
	public boolean wojskowy;
	
	
	
	public Osoba() {
		super();
		// TODO Auto-generated constructor stub
	}

	public void wiek() {
	
	}
	
	public void isWoskowy() {
	
	}
	
	
	public Osoba(long pesel, String imie, String nazwisko) {
		super();
		this.pesel = pesel;
		this.imie = imie;
		this.nazwisko = nazwisko.toUpperCase();
	}

	@Override
	public String toString() {
		// TODO Auto-generated method stub
		return imie+" " + nazwisko;
	}
	
	
}
