package amw.informatyka.zadanie1;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : PracownikNaukowy.java
//  @ Date : 2017-12-22
//  @ Author : 
//
//




public class PracownikNaukowy extends Pracownik {
	public String stNaukowy;
	public int pensum;
	
	
	public PracownikNaukowy(long pesel, String imie, String nazwisko, String stanowisko, String stopien) {
		super(pesel, imie, nazwisko, stanowisko);
		this.stNaukowy = stopien;
	}


	@Override
	public String toString() {
		// TODO Auto-generated method stub
		return stNaukowy + " " + super.toString();
	}
	
	
}
